[package]
name = "mbed"
version = "0.1.0"
authors = ["Paras Lohani <paraslohani@iisc.ac.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
